replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: false

httpRoute:
  enabled: false
  parentRefs: []
  hostnames: []
  rules: []
  annotations: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

podAnnotations: {}
podLabels: {}
imagePullSecrets: []
podSecurityContext: {}
securityContext: {}
resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}