replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http

httpRoute:
  enabled: false
  parentRefs: []
  hostnames: []
  rules: []
  annotations: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
imagePullSecrets: []
podSecurityContext: {}
securityContext: {}
resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}