replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

//Esto es para manejar la capacidad del autoescalado según el tráfico que haya - más uso de CPU más pods y menos uso pues menos pods
autoscaling:
  enabled: false

//Esto es para comprobar si la app sigue viva - si no responde reinicia el pod
  livenessProbe:
  httpGet:
    path: /actuator/health
    port: http

//Esto es para ver si está preparada para recibir tráfico - Si está arrancando no le envies peticiones todavía
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http