replicaCount: 1

containerPort: 80

image:
  repository: "docker.io/library/credia-frontend"
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

#test
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: false

httpRoute:
  enabled: false
  parentRefs: []
  hostnames: []
  rules: []
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []