replicaCount: 1

containerPort: 80

image:
  repository: 123456789.dkr.ecr.eu-west-1.amazonaws.com/credia-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
